### ISSUE TITLE
RBAC feature should also provide minimally needed roles

### ISSUE THREAD

**Issue by ankon** [coreos/kube-aws#230]
I enabled the RBAC feature, and then found that "everything was broken" :)

- the worker nodes couldn't connect to the api server until I provided a ClusterRoleBinding from User 'kube-worker' to ClusterRole 'system:node'
- the kube-dns pod and the dashboard pods failed and restarted because they couldn't connect to the API server, with errors indicating that the api server IP 10.3.0.1 is completely not known (`dial tcp 10.3.0.1:443 i/o timeout`). It turned out that that was true: kube-proxy was unable to talk to the API server and get the endpoints, and therefore failed to setup any iptables rules. It took me a long time to figure out how the networking is supposed to work, and then only by accident did I notice that issue.

This is my "minimal" role bindings so far:
```yaml
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  name: worker-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node
subjects:
- kind: User
  name: "kube-worker"
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  name: worker-node-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-proxier
subjects:
- kind: User
  name: "kube-worker"
```

It would be great if this could be provided by default, and/or at least pointed to in cluster.yaml.

**Comment by ankon** [comment]
Additionally this set was needed for making kube-dns etc actually work:

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: kube-system-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: kube-system-service-account-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-system-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kube-system
```

Based on https://blog.kcluster.io/setup-role-based-access-control-rbac-and-audit-logs-for-kubernetes-clusters-9e4db5b67020

**Comment by whereisaaron** [comment]
Great @ankon, I'd _love_ to know what the actual minimal RBAC permissions required for a functioning `kube-aws` install were. But while I'd like those as an install option or an example, I think the default `kube-aws` should include more open permissions, to enable everything to work just as if RBAC was not enabled.

If minimal permissions are applied by default, new users are going to get frustrated if they have to craft more RBAC resources to do every little thing :smile: None of the k8s examples they try are going to work, and often all that will happen is that they'll disable RBAC immediately rather than have to learn RBAC just to run a `busybox` test container. Better they launch a cluster with the RBAC capability enabled by default, and restrict access once they are familiar - is my thinking.

I used to use the below resources as the null-impact permissions for enabling RBAC on a `kube-aws` cluster build. I say 'used to' because apparently we can no longer specify 'resources' and 'nonResourceURLs' in the same role any more? So I guess I need twice and many roles and bindings for this base set-up now? 😭  (unless anyone knows a better way of handling that? ❓ )

Maybe the default `kube-aws` install could be with RBAC installed, with your minimal permissions, but plus an extra couple of role binding that open everything up again. Then to get a good restriction users could simply delete the couple of suggestively names resources (`name: make-default-namespace-unsecured`) and add their own specific permissions?

```
#
# These RBAC permissions open up the cluster as if RBAC was not enabled:
# The 'kube-admin' and 'kube-worker' users have full access
# The 'kube-system/default' and 'default/default' ServiceAccounts have full access
# This is a starting point to craft tighter permissions
#

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
    name: full-access
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
    nonResourceURLs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: kube-admin
subjects:
  - kind: User
    name: kube-admin
roleRef:
  kind: ClusterRole
  name: full-access
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: kube-worker
subjects:
  - kind: User
    name: kube-worker
roleRef:
  kind: ClusterRole
  name: full-access
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: system-default-service-account
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: default
roleRef:
  kind: ClusterRole
  name: full-access
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: default-service-account
subjects:
  - kind: ServiceAccount
    namespace: default
    name: default
roleRef:
  kind: ClusterRole
  name: full-access
  apiGroup: rbac.authorization.k8s.io
```

**Comment by ankon** [comment]
> If minimal permissions are applied by default, new users are going to get frustrated if they have to craft more RBAC resources to do every little thing

That does sound awfully familiar ... :)

Indeed, having a good OOB experience is really important, but for production at one point you should understand RBAC and work with the minimal permissions _for your problem_ only. I think that it would make sense to just document these, and describe how to start a RBAC-enabled cluster without any "convenience" roles and bindings.

**Comment by whereisaaron** [comment]
How about this for an agena?

- [ ] Write a 'How to Enable and Bootstrap RBAC' page for the 'Documentation' folder with example permissions
- [ ] Create an `experimental.rbac` option for `cluster.yaml` to enable RBAC, with option to install: 
  - [ ] No permissions
  - [ ] Minimal, cluster works, workers can join permissions
  - [ ] Fully open permissions
- [ ] Convince `kube-aws` community to enable RBAC by default, with some consensus level of initial permissions

With a side project of, what are the RBAC 'Minimal, cluster works, workers can join permissions' anyway? 🤣

**Comment by ankon** [comment]
That really sounds like a good plan!

Need to think a bit about it further, but maybe I can help here - at least my memory of what to do is still fresh ;)

**Comment by whereisaaron** [comment]
Here's an example a typical users OOB experience with RBAC, a lot of wasted time due no OOB/bootstrap permissions: kubernetes/kubernetes/issues/38997

What unites you, me, and this person, is that even after getting RBAC working, we still don't know what permissions are actually minimally required by the cluster. 😕

**Comment by whereisaaron** [comment]
@ankon our new best friend @uruddarraju has done a lot of the work towards the RBAC policies we need for `kubw-aws`: https://github.com/uruddarraju/kubernetes-rbac-policies

**Comment by whereisaaron** [comment]
If you don't have RBAC or similar, then every container gets 'root' access to the entire cluster by default. When you enable RBAC with `kube-aws` nothing works. You can contact the controller, but worker nodes are blocks from even registering.

These are the bootstrap permissions I use to enable a k8s 1.5.x cluster to start working when you have RBAC enabled. Once you add these permission the worker nodes will be able to register with the controller. It provides no access for the default namespace, default Service Account, so user Pods launched in the default namespace will not have any k8s api access by default. Which is good 😄 

```
#
# These RBAC permissions enable the cluster to operate, but restrict the default/default Service
# The 'kube-admin' and 'kube-worker' users have full access
# The 'kube-system/default' ServiceAccount has full access (used by the default kube-system Pods)
# The 'default/default' ServiceAccount has no access, and so can only pull public or ECR images
#

#
# ClusterRole's
#

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
    name: full-access
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]  
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
    name: read-access
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["*"]
    verbs: ["get", "list", "watch"]
---
#
# ClusterRoleBindings's
#

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: kube-admin
subjects:
  - kind: User
    name: kube-admin
roleRef:
  kind: ClusterRole
  name: full-access
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: kube-worker
subjects:
  - kind: User
    name: kube-worker
roleRef:
  kind: ClusterRole
  name: full-access
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: system-default-service-account
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: default
roleRef:
  kind: ClusterRole
  name: full-access
  apiGroup: rbac.authorization.k8s.io
```
