### ISSUE TITLE
0.9.4-rc.2: Only create 1 managed NatGateway per AZ

### ISSUE THREAD

**Issue by drock** [coreos/kube-aws#302]
The new flexibility of how you can create and manage subnets with/without managed NATGateways is really great.  IMHO there is only one downside however.  If you let kube-aws manage the NATGateways for private subnets, it creates 1 NATGateway per subnet.

This causes slight problems if you define a lot of private subnets in your cluster.yaml.  In my use case I have 6 private subnets (3 in each of 2 AZ's).  This produces 6 NATGateways when I really only need 2 ( 1 for each AZ for high availability).  This produces slightly higher costs but more importantly puts you more easily in reach of Amazon's resource limits on NATGateways.

**Comment by mumoshu** [comment]
@drock Sorry for the silence and thanks for the suggestion.

I guess we can also complicate (😋) cluster.yaml to support something like:

```yaml
natGateways:
- name: managedNAT1a
  availabilityZone: us-west-1a

subnets:
- name: managedPrivateSubnetForFoo1a
  # *snip*
  natGateway:
    name: managedNAT1a
- name: managedPrivateSubnetForBar1a
  # *snip*
  natGateway:
    name: managedNAT1a
```

to define NAT gateways and reference ones from subnet definitions.

Do you have any preference and this and #303 and even another ideas?
