### ISSUE TITLE
Node pools created to wrong subnet

### ISSUE THREAD

**Issue by pettair** [coreos/kube-aws#400]
Hi

I try to setup a minimal cluster into an existing VPC with 1 controller 1 etcd and 2 workerd nodes. SoI try to define a public subnet for the controller and etcd nodes and 2 private subnets in different AZs for the workers in the cluster.yml. All of the 3 subnets are created but the worker nodes are placed into the same public network as the controller and etcd nodes.
Im on v0.9.4 version of the kube-aws, and here is my configuration:
```
controller:
  autoScalingGroup:
    minSize: 1
    maxSize: 3
    rollingUpdateMinInstancesInService: 2
  subnets:
    - name: ManagedPublicSubnet1
worker:
  nodePools:
    - name: nodepool1
      count: 1
      subnet:
      - name: ManagedPrivateSubnet1
      autoScalingGroup:
        minSize: 1
        maxSize: 3
        rollingUpdateMinInstancesInService: 2
    - name: nodepool2
      count: 1
      subnet:
      - name: ManagedPrivateSubnet2
      autoScalingGroup:
        minSize: 1
        maxSize: 3
        rollingUpdateMinInstancesInService: 2
subnets:
  - name: ManagedPublicSubnet1
    availabilityZone: us-east-1a
    instanceCIDR: "10.0.100.0/24"
    routeTable:
      id: <existing_route_table_id>
  - name: ManagedPrivateSubnet1
    private: true
    availabilityZone: us-east-1a
    instanceCIDR: "10.0.101.0/24"
    natGateway:
      id: <existing_nat_gateway_id>
  - name: ManagedPrivateSubnet2
    private: true
    availabilityZone: us-east-1b
    instanceCIDR: "10.0.102.0/24"
    natGateway:
      id: <existing_nat_gateway_id>
```

and the generated cloudformation template:
NodePool1
```
"Workers": {
	"Properties": {
		....
		"Tags": [{
			...
			}, {
				"Key": "kube-aws:node-pool:name",
				"PropagateAtLaunch": "true",
				"Value": "nodepool1"
			}, {
			...
		],
		"VPCZoneIdentifier": [{
				"Fn::ImportValue": {
					"Fn::Sub": "${ControlPlaneStackName}-ManagedPublicSubnet1"
				}
			}
		]
	},
	"Type": "AWS::AutoScaling::AutoScalingGroup",
	...
},
```
NodePool2:
```
"Workers": {
	"Properties": {
		...
		"Tags": [{
			...
				"Key": "kube-aws:node-pool:name",
				"PropagateAtLaunch": "true",
				"Value": "nodepool2"
			}, {
			...
		],
		"VPCZoneIdentifier": [{
				"Fn::ImportValue": {
					"Fn::Sub": "${ControlPlaneStackName}-ManagedPublicSubnet1"
				}
			}
		]
	},
	...
},
```

Do you have any idea what could go wrong here?
