### ISSUE TITLE
Cluster autoscaling with a more AWS-native way?

### ISSUE THREAD

**Issue by pettair** [coreos/kube-aws#407]
I created my node pools with the following configuration:
```yaml
worker:
  nodePools:
    - name: nodepool1
      count: 1
      subnet:
      - name: ManagedPrivateSubnet1
      autoScalingGroup:
        minSize: 1
        maxSize: 3
        rollingUpdateMinInstancesInService: 2
    - name: nodepool2
      count: 1
      subnet:
      - name: ManagedPrivateSubnet2
      autoScalingGroup:
        minSize: 1
        maxSize: 3
        rollingUpdateMinInstancesInService: 2
```

The two ASGs and Launch Configuration are created for each of the two pools but there is no scaling policy created.
So when kubernetes autoscale kicks in and starts to fill up the instances, the ASG wont initiate new instances.
